Fix flaky error in test_configuration (#685)
When running test case 'test_configuration', sometimes it will fail.

There is the error message when calling
plcontainer_containers_summary:
ERROR: plcontainer: Fail to get docker container state: Failed to get
container xxxx state, return code: 404, detail: {"message":"No such
container: xxxx"} (plc_container_info.c:525)

So, maybe there is a such situation:
 1. plcontainer_containers_summary call c function containers_summary
 2. containers_summary will call plc_docker_list_container.
 3. plc_docker_list_container will list all docker containers like
    docker containers ls -al without filter status.
 4. If plc_docker_list_container get a container which is removing, and
    then plcontainer will use docker api to get information of this
    removing container, but maybe the container has been removed at that
    time, so docker return error.

To solve this problem, let 'containers_summary' return the 'Has been
removed' status when docker api return 404.

To reproduce:
 1. add a sleep in containers_summary after plc_docker_list_container,
 2. for example, sleep 2 seconds
 3. open a session with psql xx
 4. run a plcontainer udf
 5. exit session
 6. open a session again and call plcontainer_containers_summary quickly.